# madar.hamedco.com - agents bot WebApp
server {
    server_name madar.hamedco.com;

    location = / {
        return 302 /webapp/agents;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/madar.hamedco.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/madar.hamedco.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = madar.hamedco.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name madar.hamedco.com;
    return 404;
}

# madar.azeez-tech.com - agents bot WebApp
server {
    server_name madar.azeez-tech.com;

    location = / {
        return 302 /webapp/agents;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/madar.azeez-tech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/madar.azeez-tech.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = madar.azeez-tech.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name madar.azeez-tech.com;
    return 404;
}
